# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Rasterwise Blog
subtitle: Learn how to use Rasterwise APIs
description: Learn how to use Rasterwise APIs
keywords: screenshot api, screenshot, image api
author: Rasterwise
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.rasterwise.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: docs
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
# highlight:
#   enable: true
#   line_number: true
#   auto_detect: false
#   tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: overdose

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:


# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives

# Images
favicon: /images/avatar.png
## Post default banner image
## Please specify width and height for google's structured data (Schema.org SEO)
default:
  url: /images/default.jpg
  width: 1280
  height: 720


# Dynamic menu with scrolling
dynamic_menu: false

# Highlight theme
## You can also use various themes in `css/highlights`
highlight: dracula

# Related posts
## If you don't want `related posts` feature, you should specify the value as 0.
## If you want more related posts, you can do it too.
## But I don't recommend to specify over than 3.
related_posts: 3 # default enabled as 3

# Profile
profile:
  image: /images/avatar.png
  gravatar:
  link:
  description:
  social:
    github:
    facebook: # Facebook property also used in `article:author` meta tag.
    linkedin:
    instagram:
    twitter:
    rss: /atom.xml

# Footer widgets
## Don't use over than 3 widgets.
## availableWidgetList: [
##   'archives',
##   'categories',
##   'recent-posts',
##   'tag-cloud',
##   'tags'
## ]
## If you don't want widget, you shouldn't specify widgets.
widgets:
  - recent-posts
  - archives
  - categories

# Other Services
google_analytics: UA-135545408-2
google_site_verification:
naver_site_verification:

# Open graph
facebook:
fb_admin:
twitter:
google_plus:

#liveRe
liveRe:
  uid:

