# basic
title: Rasterwise Blog
subtitle: Tutorials, Thoughts and More
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: /images/avatar.png
# banner_small: http://7xrcp8.com1.z0.glb.clouddn.com/banner-small.png
# banner_large: http://7xrcp8.com1.z0.glb.clouddn.com/banner-large.png

# disqus
# disqus_shortname: drakeleung

# social
social:
  github: https://github.com/whoisjuan/rasterwise-blog

# nav #
nav:
  home: .
  archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


google_analytics: # Put tracking ID here
